-- MySQL Script generated by MySQL Workbench
-- Thu Sep 28 00:20:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tccapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tccapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tccapp` DEFAULT CHARACTER SET utf8mb3 ;
USE `tccapp` ;

-- -----------------------------------------------------
-- Table `tccapp`.`conteudo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`conteudo` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`conteudo` (
  `ID_CONTEUDO` INT NOT NULL AUTO_INCREMENT,
  `NOME_CONTEUDO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_CONTEUDO`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tccapp`.`questao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`questao` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`questao` (
  `ID_QUESTAO` INT NOT NULL AUTO_INCREMENT,
  `TEXTO_QUESTAO` VARCHAR(255) NOT NULL,
  `NIVEL_QUESTAO` FLOAT NULL DEFAULT NULL,
  `CONTEUDO_ID_CONTEUDO` INT NOT NULL,
  PRIMARY KEY (`ID_QUESTAO`),
  INDEX `fk_QUESTAO_CONTEUDO1_idx` (`CONTEUDO_ID_CONTEUDO` ASC) VISIBLE,
  CONSTRAINT `fk_QUESTAO_CONTEUDO1`
    FOREIGN KEY (`CONTEUDO_ID_CONTEUDO`)
    REFERENCES `tccapp`.`conteudo` (`ID_CONTEUDO`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tccapp`.`alternativas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`alternativas` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`alternativas` (
  `ID_ALTERNATIVAS` INT NOT NULL AUTO_INCREMENT,
  `QUESTAO_ID_QUESTAO` INT NOT NULL,
  `ALTER_TEXTO` VARCHAR(255) NOT NULL,
  `ALTER_CORR` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_ALTERNATIVAS`),
  INDEX `fk_ALTERNATIVAS_QUESTAO_idx` (`QUESTAO_ID_QUESTAO` ASC) VISIBLE,
  CONSTRAINT `fk_ALTERNATIVAS_QUESTAO`
    FOREIGN KEY (`QUESTAO_ID_QUESTAO`)
    REFERENCES `tccapp`.`questao` (`ID_QUESTAO`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tccapp`.`disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`disciplina` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`disciplina` (
  `ID_DISCIPLINA` INT NOT NULL AUTO_INCREMENT,
  `NOME_DISCIPLINA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_DISCIPLINA`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tccapp`.`conteudo_has_disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`conteudo_has_disciplina` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`conteudo_has_disciplina` (
  `CONTEUDO_ID_CONTEUDO` INT NOT NULL,
  `DISCIPLINA_ID_DISCIPLINA` INT NOT NULL,
  PRIMARY KEY (`CONTEUDO_ID_CONTEUDO`, `DISCIPLINA_ID_DISCIPLINA`),
  INDEX `fk_CONTEUDO_has_DISCIPLINA_DISCIPLINA1_idx` (`DISCIPLINA_ID_DISCIPLINA` ASC) VISIBLE,
  INDEX `fk_CONTEUDO_has_DISCIPLINA_CONTEUDO1_idx` (`CONTEUDO_ID_CONTEUDO` ASC) VISIBLE,
  CONSTRAINT `fk_CONTEUDO_has_DISCIPLINA_CONTEUDO1`
    FOREIGN KEY (`CONTEUDO_ID_CONTEUDO`)
    REFERENCES `tccapp`.`conteudo` (`ID_CONTEUDO`),
  CONSTRAINT `fk_CONTEUDO_has_DISCIPLINA_DISCIPLINA1`
    FOREIGN KEY (`DISCIPLINA_ID_DISCIPLINA`)
    REFERENCES `tccapp`.`disciplina` (`ID_DISCIPLINA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tccapp`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`curso` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`curso` (
  `ID_CURSO` INT NOT NULL AUTO_INCREMENT,
  `NOME_CURSO` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_CURSO`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tccapp`.`disciplina_has_curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`disciplina_has_curso` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`disciplina_has_curso` (
  `DISCIPLINA_ID_DISCIPLINA` INT NOT NULL,
  `CURSO_ID_CURSO` INT NOT NULL,
  PRIMARY KEY (`DISCIPLINA_ID_DISCIPLINA`, `CURSO_ID_CURSO`),
  INDEX `fk_DISCIPLINA_has_CURSO_CURSO1_idx` (`CURSO_ID_CURSO` ASC) VISIBLE,
  INDEX `fk_DISCIPLINA_has_CURSO_DISCIPLINA1_idx` (`DISCIPLINA_ID_DISCIPLINA` ASC) VISIBLE,
  CONSTRAINT `fk_DISCIPLINA_has_CURSO_CURSO1`
    FOREIGN KEY (`CURSO_ID_CURSO`)
    REFERENCES `tccapp`.`curso` (`ID_CURSO`),
  CONSTRAINT `fk_DISCIPLINA_has_CURSO_DISCIPLINA1`
    FOREIGN KEY (`DISCIPLINA_ID_DISCIPLINA`)
    REFERENCES `tccapp`.`disciplina` (`ID_DISCIPLINA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
