-- MySQL Script generated by MySQL Workbench
-- Wed Oct  4 01:35:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tccapp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tccapp` ;

-- -----------------------------------------------------
-- Schema tccapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tccapp` DEFAULT CHARACTER SET utf8mb3 ;
USE `tccapp` ;

-- -----------------------------------------------------
-- Table `tccapp`.`DISCIPLINA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`DISCIPLINA` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`DISCIPLINA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME_DISCIPLINA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tccapp`.`CONTEUDO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`CONTEUDO` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`CONTEUDO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME_CONTEUDO` VARCHAR(45) NOT NULL,
  `DISCIPLINA_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `DISCIPLINA_ID`),
  INDEX `fk_CONTEUDO_DISCIPLINA1_idx` (`DISCIPLINA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CONTEUDO_DISCIPLINA1`
    FOREIGN KEY (`DISCIPLINA_ID`)
    REFERENCES `tccapp`.`DISCIPLINA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tccapp`.`QUESTAO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`QUESTAO` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`QUESTAO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TEXTO_QUESTAO` VARCHAR(255) NOT NULL,
  `NIVEL_QUESTAO` INT NULL,
  `CONTEUDO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_QUESTAO_CONTEUDO1_idx` (`CONTEUDO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_QUESTAO_CONTEUDO1`
    FOREIGN KEY (`CONTEUDO_ID`)
    REFERENCES `tccapp`.`CONTEUDO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tccapp`.`ALTERNATIVA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`ALTERNATIVA` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`ALTERNATIVA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ALTER_TEXTO` VARCHAR(255) NOT NULL,
  `ALTER_CORR` TINYINT(1) NOT NULL,
  `QUESTAO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ALTERNATIVA_QUESTAO1_idx` (`QUESTAO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ALTERNATIVA_QUESTAO1`
    FOREIGN KEY (`QUESTAO_ID`)
    REFERENCES `tccapp`.`QUESTAO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tccapp`.`CURSO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`CURSO` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`CURSO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME_CURSO` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tccapp`.`CURSO_has_DISCIPLINA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`CURSO_has_DISCIPLINA` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`CURSO_has_DISCIPLINA` (
  `CURSO_ID` INT NOT NULL,
  `DISCIPLINA_ID` INT NOT NULL,
  PRIMARY KEY (`CURSO_ID`, `DISCIPLINA_ID`),
  INDEX `fk_CURSO_has_DISCIPLINA_DISCIPLINA1_idx` (`DISCIPLINA_ID` ASC) VISIBLE,
  INDEX `fk_CURSO_has_DISCIPLINA_CURSO1_idx` (`CURSO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CURSO_has_DISCIPLINA_CURSO1`
    FOREIGN KEY (`CURSO_ID`)
    REFERENCES `tccapp`.`CURSO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURSO_has_DISCIPLINA_DISCIPLINA1`
    FOREIGN KEY (`DISCIPLINA_ID`)
    REFERENCES `tccapp`.`DISCIPLINA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
