-- MySQL Script generated by MySQL Workbench
-- Mon Oct 23 17:06:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tccapp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tccapp` ;

-- -----------------------------------------------------
-- Schema tccapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tccapp` DEFAULT CHARACTER SET utf8mb3 ;
USE `tccapp` ;

-- -----------------------------------------------------
-- Table `tccapp`.`DISCIPLINA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`DISCIPLINA` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`DISCIPLINA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME_DISCIPLINA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tccapp`.`CONTEUDO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`CONTEUDO` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`CONTEUDO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME_CONTEUDO` VARCHAR(45) NOT NULL,
  `DISCIPLINA_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_CONTEUDO_DISCIPLINA1_idx` (`DISCIPLINA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CONTEUDO_DISCIPLINA1`
    FOREIGN KEY (`DISCIPLINA_ID`)
    REFERENCES `tccapp`.`DISCIPLINA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tccapp`.`QUESTAO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`QUESTAO` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`QUESTAO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TEXTO_QUESTAO` VARCHAR(255) NOT NULL,
  `NIVEL_QUESTAO` INT NULL,
  `CONTEUDO_ID` INT NOT NULL,
  `DISCIPLINA_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_QUESTAO_CONTEUDO1_idx` (`CONTEUDO_ID` ASC, `DISCIPLINA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_QUESTAO_CONTEUDO1`
    FOREIGN KEY (`CONTEUDO_ID` , `DISCIPLINA_ID`)
    REFERENCES `tccapp`.`CONTEUDO` (`ID` , `DISCIPLINA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tccapp`.`ALTERNATIVA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`ALTERNATIVA` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`ALTERNATIVA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ALTER_TEXTO` VARCHAR(255) NOT NULL,
  `ALTER_CORR` TINYINT(1) NOT NULL,
  `QUESTAO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ALTERNATIVA_QUESTAO1_idx` (`QUESTAO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ALTERNATIVA_QUESTAO1`
    FOREIGN KEY (`QUESTAO_ID`)
    REFERENCES `tccapp`.`QUESTAO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tccapp`.`CURSO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`CURSO` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`CURSO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME_CURSO` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tccapp`.`CURSO_has_DISCIPLINA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`CURSO_has_DISCIPLINA` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`CURSO_has_DISCIPLINA` (
  `CURSO_ID` INT NOT NULL,
  `DISCIPLINA_ID` INT NOT NULL,
  PRIMARY KEY (`CURSO_ID`, `DISCIPLINA_ID`),
  INDEX `fk_CURSO_has_DISCIPLINA_DISCIPLINA1_idx` (`DISCIPLINA_ID` ASC) VISIBLE,
  INDEX `fk_CURSO_has_DISCIPLINA_CURSO1_idx` (`CURSO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CURSO_has_DISCIPLINA_CURSO1`
    FOREIGN KEY (`CURSO_ID`)
    REFERENCES `tccapp`.`CURSO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURSO_has_DISCIPLINA_DISCIPLINA1`
    FOREIGN KEY (`DISCIPLINA_ID`)
    REFERENCES `tccapp`.`DISCIPLINA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tccapp`.`ALUNO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`ALUNO` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`ALUNO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(50) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tccapp`.`HIST_PROVA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`HIST_PROVA` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`HIST_PROVA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `GAB_CODE` MEDIUMTEXT NULL,
  `DATA_PROVA` DATE NOT NULL,
  `ALUNO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_HIST_PROVA_ALUNO1_idx` (`ALUNO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_HIST_PROVA_ALUNO1`
    FOREIGN KEY (`ALUNO_ID`)
    REFERENCES `tccapp`.`ALUNO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tccapp`.`MATRICULA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`MATRICULA` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`MATRICULA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `STATUS` ENUM('CURSANDO', 'APROVADO', 'REPROVADO') NULL,
  `QUANT_REPROVADO` INT NULL,
  `DISCIPLINA_ID` INT NOT NULL,
  `ALUNO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_MATRICULA_DISCIPLINA1_idx` (`DISCIPLINA_ID` ASC) VISIBLE,
  INDEX `fk_MATRICULA_ALUNO1_idx` (`ALUNO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_MATRICULA_DISCIPLINA1`
    FOREIGN KEY (`DISCIPLINA_ID`)
    REFERENCES `tccapp`.`DISCIPLINA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATRICULA_ALUNO1`
    FOREIGN KEY (`ALUNO_ID`)
    REFERENCES `tccapp`.`ALUNO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tccapp`.`NOTAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`NOTAS` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`NOTAS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOTA` DOUBLE NULL,
  `ALUNO_ID` INT NOT NULL,
  `CONTEUDO_ID` INT NOT NULL,
  `DISCIPLINA_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_NOTAS_ALUNO1_idx` (`ALUNO_ID` ASC) VISIBLE,
  INDEX `fk_NOTAS_CONTEUDO1_idx` (`CONTEUDO_ID` ASC, `DISCIPLINA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_NOTAS_ALUNO1`
    FOREIGN KEY (`ALUNO_ID`)
    REFERENCES `tccapp`.`ALUNO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NOTAS_CONTEUDO1`
    FOREIGN KEY (`CONTEUDO_ID` , `DISCIPLINA_ID`)
    REFERENCES `tccapp`.`CONTEUDO` (`ID` , `DISCIPLINA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tccapp`.`PROFESSOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`PROFESSOR` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`PROFESSOR` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME_PROFESSOR` VARCHAR(60) NULL,
  `LOGIN_PROFESSOR` VARCHAR(45) NULL,
  `SENHA_PROFESSOR` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tccapp`.`TURMA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`TURMA` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`TURMA` (
  `ID_TURMA` INT NOT NULL AUTO_INCREMENT,
  `NOME_TURMA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_TURMA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tccapp`.`PROFESSOR_has_TURMA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`PROFESSOR_has_TURMA` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`PROFESSOR_has_TURMA` (
  `PROFESSOR_ID` INT NOT NULL,
  `TURMA_ID_TURMA` INT NOT NULL,
  PRIMARY KEY (`PROFESSOR_ID`, `TURMA_ID_TURMA`),
  INDEX `fk_PROFESSOR_has_TURMA_TURMA1_idx` (`TURMA_ID_TURMA` ASC) VISIBLE,
  INDEX `fk_PROFESSOR_has_TURMA_PROFESSOR1_idx` (`PROFESSOR_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PROFESSOR_has_TURMA_PROFESSOR1`
    FOREIGN KEY (`PROFESSOR_ID`)
    REFERENCES `tccapp`.`PROFESSOR` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROFESSOR_has_TURMA_TURMA1`
    FOREIGN KEY (`TURMA_ID_TURMA`)
    REFERENCES `tccapp`.`TURMA` (`ID_TURMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tccapp`.`TURMA_has_MATRICULA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tccapp`.`TURMA_has_MATRICULA` ;

CREATE TABLE IF NOT EXISTS `tccapp`.`TURMA_has_MATRICULA` (
  `TURMA_ID_TURMA` INT NOT NULL,
  `MATRICULA_ID` INT NOT NULL,
  PRIMARY KEY (`TURMA_ID_TURMA`, `MATRICULA_ID`),
  INDEX `fk_TURMA_has_MATRICULA_MATRICULA1_idx` (`MATRICULA_ID` ASC) VISIBLE,
  INDEX `fk_TURMA_has_MATRICULA_TURMA1_idx` (`TURMA_ID_TURMA` ASC) VISIBLE,
  CONSTRAINT `fk_TURMA_has_MATRICULA_TURMA1`
    FOREIGN KEY (`TURMA_ID_TURMA`)
    REFERENCES `tccapp`.`TURMA` (`ID_TURMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TURMA_has_MATRICULA_MATRICULA1`
    FOREIGN KEY (`MATRICULA_ID`)
    REFERENCES `tccapp`.`MATRICULA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
